### PR TITLE
fix(web): Keep map bounds consistent and updated

### LINKED ISSUE #145: Map bounds should be consistent and updated.
### Expected Behavior

Map bounds and centre are correct.

### Current Behavior

> minor issue is the bounds load differently when you go to menu and come back vs refresh. refresh displays it right but it's small

Also, map centering is inconsistent, sometimes is set to SCU with other locations out of bound.

### PR DESCRIPTION
**Pull request by pbebla**
### Description

Map bounds stay consistent, refresh or navigating to another page and back.

### Tested

Tested both scenarios.

### Related issues

* Fixes #145

### CODE REVIEW

File: packages/web/src/components/MapView.tsx [hunk 1]
```diff
@@ -11,6 +11,12 @@ const defaultMapOptions = {
     },
     zoom: 13,
 };
+const mapOptions = {
```
Comment (drklee3) [inline packages/web/src/components/MapView.tsx]: I think it would be better if we put the mapOptions in `MapViewState` and avoid using global variables.  Did you try that?  Since you'd need to use `this.setState()`, you could just move the entire `getMapBounds()` as a member function of the `MapView` class.

Comment (pbebla) [reply packages/web/src/components/MapView.tsx]: No, I haven't thought about that. I'll try that.

Comment (pbebla) [reply packages/web/src/components/MapView.tsx]: If I add mapOptions to MapViewState, I get errors in getDerivedStatefromProps where when I create a polyline and return the polyline, it wants to also set the center property.

Comment (drklee3) [reply packages/web/src/components/MapView.tsx]: When returning?  Is mapOptions set to be nullable?  Something like 

```javascript
interface MapViewState {
    map?: google.maps.Map;
    maps?: typeof google.maps;
    polyline?: google.maps.Polyline;
    lat?: number,
    lng?: number,
}
```

**Review by drklee3 — APPROVED** [review]
LGTM! Works well, nice job
